version: "3.9"
services:
  qtbot:
    network_mode: host
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /qtbot
    env_file:
      - .env
  redis:
    image: redis
    restart: always
    ports:
      - "6739:6739"
